## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: mkborregaard@snm.ku.dk
git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

script:
  - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("RandomBooleanMatrices"); Pkg.test("RandomBooleanMatrices")'
